# ===================================================================
# Fichero de configuración Entorno Producción
# ===================================================================

# # ===============================
# = HTTP Server
# # ===============================
server:
  port: 9080

# # ===============================
# = SPRING BOOT GENERAL
# # ===============================
spring:
  profiles:
    active: pro