# ===================================================================
# Fichero de configuración Entorno Desarrollo
# ===================================================================

# # ===============================
# = HTTP Server
# # ===============================
server:
  port: 8080

# # ===============================
# = SPRING BOOT GENERAL
# # ===============================
spring:
  profiles:
    active: dev